// DESIGN.md front matter -> src/tokens.ts + src/tokens.css (eng review 6A).
// Colours are written once (DESIGN.md) and read by both CSS and the 3D scene.

import { parse } from 'yaml';

export interface DesignTokens {
  name: string;
  colors: Record<string, string>;
  rounded: Record<string, string>;
  spacing: Record<string, string>;
}

const HEX = /^#[0-9a-fA-F]{6}$/;

export function parseDesignMd(md: string): DesignTokens {
  const m = /^---\n([\s\S]*?)\n---/.exec(md);
  if (!m) throw new Error('DESIGN.md: no front matter');
  const fm = parse(m[1]!) as Record<string, unknown>;
  const colors = fm.colors as Record<string, string> | undefined;
  if (!colors || typeof colors !== 'object') throw new Error('DESIGN.md: colors missing');
  for (const [k, v] of Object.entries(colors)) {
    if (typeof v !== 'string' || !HEX.test(v)) throw new Error(`DESIGN.md: colors.${k} must be #rrggbb (got ${String(v)})`);
  }
  return {
    name: String(fm.name ?? ''),
    colors,
    rounded: (fm.rounded as Record<string, string>) ?? {},
    spacing: (fm.spacing as Record<string, string>) ?? {},
  };
}

const HEADER = '// GENERATED by scripts/build-tokens.ts from DESIGN.md. Do not edit; run `npm run build:tokens`.\n';

export function renderTokensTs(t: DesignTokens): string {
  return `${HEADER}
export const colors = ${JSON.stringify(t.colors, null, 2)} as const;
export type ColorToken = keyof typeof colors;

export const rounded = ${JSON.stringify(t.rounded, null, 2)} as const;
export const spacing = ${JSON.stringify(t.spacing, null, 2)} as const;
`;
}

export function renderTokensCss(t: DesignTokens): string {
  const lines = [
    ...Object.entries(t.colors).map(([k, v]) => `  --color-${k}: ${v};`),
    ...Object.entries(t.rounded).map(([k, v]) => `  --rounded-${k}: ${v};`),
    ...Object.entries(t.spacing).map(([k, v]) => `  --space-${k}: ${v};`),
  ];
  return `/* GENERATED by scripts/build-tokens.ts from DESIGN.md. Do not edit; run \`npm run build:tokens\`. */\n:root {\n${lines.join('\n')}\n}\n`;
}
