// npm run build:data
// Validates the sourced numbers and writes public/data/constants.json. Fails the build on any problem.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { buildConstants, buildCountries, buildHubs, buildSeries, DataValidationError, type ChangelogEntry } from './lib/build';
import type { Constants, HubsFile } from '../src/footprint/types';
import type { CountriesFile, SeriesFile } from '../src/footprint/series-types';
import { renderPage } from '../src/how/render';

const SOURCE = 'data/sources/constants.source.json';
const OUT = 'public/data/constants.json';
const CHANGELOG = 'public/data/changelog.json'; // public: How We Know shows it
const HUBS_SOURCE = 'data/sources/hubs.source.json';
const HUBS_OUT = 'public/data/hubs.json';
const SERIES_SOURCE = 'data/sources/series.source.json';
const SERIES_OUT = 'public/data/series.json';
const COUNTRIES_SOURCE = 'data/sources/countries.source.json';
const COUNTRIES_OUT = 'public/data/countries.json';
const HOW_OUT = 'src/how/content.generated.html'; // prerendered How We Know body (inlined by vite.config.ts)

const readJson = <T>(p: string): T | null => (existsSync(p) ? (JSON.parse(readFileSync(p, 'utf8')) as T) : null);

try {
  const today = new Date().toISOString().slice(0, 10);
  const { constants, changelog } = buildConstants(readJson(SOURCE), readJson<Constants>(OUT), today);
  if (!changelog) {
    console.log(`constants unchanged (v${constants.constantsVersion}, ${constants.contentHash})`);
  } else {
    writeFileSync(OUT, `${JSON.stringify(constants, null, 2)}\n`);
    const log = readJson<ChangelogEntry[]>(CHANGELOG) ?? [];
    log.push(changelog);
    writeFileSync(CHANGELOG, `${JSON.stringify(log, null, 2)}\n`);
    console.log(`wrote ${OUT} v${constants.constantsVersion} (${constants.contentHash}); ${changelog.changes.length} value(s) changed`);
  }
  const hubs = buildHubs(readJson(HUBS_SOURCE), readJson<HubsFile>(HUBS_OUT), today);
  if (!hubs) console.log('hubs unchanged');
  else {
    writeFileSync(HUBS_OUT, `${JSON.stringify(hubs, null, 2)}\n`);
    console.log(`wrote ${HUBS_OUT}: ${hubs.hubs.length} hubs (${hubs.contentHash})`);
  }
  const series = buildSeries(readJson(SERIES_SOURCE), readJson<SeriesFile>(SERIES_OUT), today);
  if (!series) console.log('series unchanged');
  else {
    writeFileSync(SERIES_OUT, `${JSON.stringify(series, null, 2)}\n`);
    console.log(`wrote ${SERIES_OUT}: ${series.firstYear}-${series.lastYear} (${series.contentHash})`);
  }
  const countries = buildCountries(readJson(COUNTRIES_SOURCE), readJson<CountriesFile>(COUNTRIES_OUT), today);
  if (!countries) console.log('countries unchanged');
  else {
    writeFileSync(COUNTRIES_OUT, `${JSON.stringify(countries, null, 2)}\n`);
    console.log(`wrote ${COUNTRIES_OUT}: ${countries.countries.length} countries, ${countries.year} (${countries.contentHash})`);
  }
  // How We Know, prerendered from exactly what the site ships.
  const html = `<!-- GENERATED by scripts/build-data.ts from public/data. Do not edit; run \`npm run build:data\`. -->\n${renderPage(
    readJson<Constants>(OUT)!,
    readJson<HubsFile>(HUBS_OUT)!.hubs,
    readJson<ChangelogEntry[]>(CHANGELOG) ?? [],
    readJson<SeriesFile>(SERIES_OUT)!,
    readJson<CountriesFile>(COUNTRIES_OUT)!,
  )}\n`;
  if (!existsSync(HOW_OUT) || readFileSync(HOW_OUT, 'utf8') !== html) {
    writeFileSync(HOW_OUT, html);
    console.log(`wrote ${HOW_OUT}`);
  }
} catch (e) {
  console.error(e instanceof DataValidationError ? e.message : e);
  process.exit(1);
}
