// npm run build:data
// Validates the sourced numbers and writes public/data/constants.json. Fails the build on any problem.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { buildConstants, buildCountries, buildGrids, buildHubs, buildSeries, DataValidationError, type ChangelogEntry } from './lib/build';
import { buildWorld } from './lib/world';
import type { Constants, GridsFile, HubsFile } from '../src/footprint/types';
import type { CountriesFile, SeriesFile } from '../src/footprint/series-types';
import { renderPage } from '../src/how/render';
import { renderHero } from '../src/present/hero';
import { extractInlineStyles } from '../src/present/inline-styles';

const SOURCE = 'data/sources/constants.source.json';
const OUT = 'public/data/constants.json';
const CHANGELOG = 'public/data/changelog.json'; // public: How We Know shows it
const HUBS_SOURCE = 'data/sources/hubs.source.json';
const HUBS_OUT = 'public/data/hubs.json';
const SERIES_SOURCE = 'data/sources/series.source.json';
const SERIES_OUT = 'public/data/series.json';
const COUNTRIES_SOURCE = 'data/sources/countries.source.json';
const COUNTRIES_OUT = 'public/data/countries.json';
const GRIDS_SOURCE = 'data/sources/grids.source.json';
const GRIDS_OUT = 'public/data/grids.json';
const WORLD_OUT = 'public/data/world.json'; // country shapes for the Earth home
const HERO_OUT = 'src/hero.generated.html'; // prebuilt first screen (inlined into index.html by vite.config.ts)
const HERO_CSS_OUT = 'src/hero.generated.css'; // its inline styles, moved out for the CSP (style-src 'self')
const HOW_OUT = 'src/how/content.generated.html'; // prerendered How We Know body (inlined by vite.config.ts)

const readJson = <T>(p: string): T | null => (existsSync(p) ? (JSON.parse(readFileSync(p, 'utf8')) as T) : null);

try {
  const today = new Date().toISOString().slice(0, 10);
  const { constants, changelog } = buildConstants(readJson(SOURCE), readJson<Constants>(OUT), today);
  if (!changelog) {
    console.log(`constants unchanged (v${constants.constantsVersion}, ${constants.contentHash})`);
  } else {
    writeFileSync(OUT, `${JSON.stringify(constants, null, 2)}\n`);
    const log = readJson<ChangelogEntry[]>(CHANGELOG) ?? [];
    log.push(changelog);
    writeFileSync(CHANGELOG, `${JSON.stringify(log, null, 2)}\n`);
    console.log(`wrote ${OUT} v${constants.constantsVersion} (${constants.contentHash}); ${changelog.changes.length} value(s) changed`);
  }
  const hubs = buildHubs(readJson(HUBS_SOURCE), readJson<HubsFile>(HUBS_OUT), today);
  if (!hubs) console.log('hubs unchanged');
  else {
    writeFileSync(HUBS_OUT, `${JSON.stringify(hubs, null, 2)}\n`);
    console.log(`wrote ${HUBS_OUT}: ${hubs.hubs.length} hubs (${hubs.contentHash})`);
  }
  const series = buildSeries(readJson(SERIES_SOURCE), readJson<SeriesFile>(SERIES_OUT), today);
  if (!series) console.log('series unchanged');
  else {
    writeFileSync(SERIES_OUT, `${JSON.stringify(series, null, 2)}\n`);
    console.log(`wrote ${SERIES_OUT}: ${series.firstYear}-${series.lastYear} (${series.contentHash})`);
  }
  const countries = buildCountries(readJson(COUNTRIES_SOURCE), readJson<CountriesFile>(COUNTRIES_OUT), today);
  if (!countries) console.log('countries unchanged');
  else {
    writeFileSync(COUNTRIES_OUT, `${JSON.stringify(countries, null, 2)}\n`);
    console.log(`wrote ${COUNTRIES_OUT}: ${countries.countries.length} countries, ${countries.year} (${countries.contentHash})`);
  }
  const grids = buildGrids(readJson(GRIDS_SOURCE), readJson<GridsFile>(GRIDS_OUT), today);
  if (!grids) console.log('grids unchanged');
  else {
    writeFileSync(GRIDS_OUT, `${JSON.stringify(grids, null, 2)}\n`);
    console.log(`wrote ${GRIDS_OUT}: ${grids.grids.length} grids (${grids.contentHash})`);
  }
  const world = `${JSON.stringify(buildWorld())}\n`;
  if (!existsSync(WORLD_OUT) || readFileSync(WORLD_OUT, 'utf8') !== world) {
    writeFileSync(WORLD_OUT, world);
    console.log(`wrote ${WORLD_OUT} (${Math.round(world.length / 1024)} KB)`);
  }
  // How We Know, prerendered from exactly what the site ships.
  const html = `<!-- GENERATED by scripts/build-data.ts from public/data. Do not edit; run \`npm run build:data\`. -->\n${renderPage(
    readJson<Constants>(OUT)!,
    readJson<HubsFile>(HUBS_OUT)!.hubs,
    readJson<ChangelogEntry[]>(CHANGELOG) ?? [],
    readJson<SeriesFile>(SERIES_OUT)!,
    readJson<CountriesFile>(COUNTRIES_OUT)!,
    readJson<GridsFile>(GRIDS_OUT)!,
  )}\n`;
  if (!existsSync(HOW_OUT) || readFileSync(HOW_OUT, 'utf8') !== html) {
    writeFileSync(HOW_OUT, html);
    console.log(`wrote ${HOW_OUT}`);
  }
  // The first screen, prebuilt from exactly what the site ships (eng review D4).
  const constantsNow = readJson<Constants>(OUT)!;
  const prebuilt = extractInlineStyles(
    renderHero({ series: readJson<SeriesFile>(SERIES_OUT)!, countries: readJson<CountriesFile>(COUNTRIES_OUT)!, constants: constantsNow }),
  );
  const banner = 'GENERATED by scripts/build-data.ts from public/data. Do not edit; run `npm run build:data`.';
  for (const [file, body] of [
    [HERO_OUT, `<!-- ${banner} -->\n${prebuilt.html}\n`],
    [HERO_CSS_OUT, `/* ${banner} */\n${prebuilt.css}`],
  ] as const) {
    if (!existsSync(file) || readFileSync(file, 'utf8') !== body) {
      writeFileSync(file, body);
      console.log(`wrote ${file}`);
    }
  }
} catch (e) {
  console.error(e instanceof DataValidationError ? e.message : e);
  process.exit(1);
}
