// GENERATED by scripts/build-tokens.ts from DESIGN.md. Do not edit; run `npm run build:tokens`.

export const colors = {
  "primary": "#C2412A",
  "on-primary": "#FFFFFF",
  "primary-pressed": "#B53A25",
  "primary-underside": "#8F2E1D",
  "surface": "#FBF4EA",
  "surface-deep": "#F3E7D6",
  "text": "#3B2F2A",
  "text-muted": "#6B5A50",
  "accent": "#FFB547",
  "accent-ember": "#FF8A3D",
  "focus": "#2F6F8A",
  "sky-dawn": "#CFE3F2",
  "sky-horizon": "#F6DCC8",
  "land": "#D9A273",
  "land-shadow": "#A8704A",
  "water": "#5FA8B8",
  "shallows": "#9FD3D0",
  "foliage": "#6E9A4F",
  "foliage-highlight": "#A9C66B",
  "brass": "#C9A45C",
  "wood": "#8A5A3B",
  "snow": "#F4EFE8",
  "sky-stressed": "#D8D2CC",
  "land-stressed": "#C7B59E",
  "water-stressed": "#8FA3A0",
  "foliage-stressed": "#9A9A6A",
  "dusk-sky": "#3E4A6B",
  "dusk-horizon": "#B7768A",
  "dusk-surface": "#2C2530",
  "dusk-text": "#F7EDE2",
  "success": "#6E9A4F",
  "warning": "#E08A1E",
  "error": "#B63F28"
} as const;
export type ColorToken = keyof typeof colors;

export const rounded = {
  "sm": "6px",
  "md": "14px",
  "lg": "18px",
  "xl": "26px",
  "full": "9999px"
} as const;
export const spacing = {
  "xs": "4px",
  "sm": "8px",
  "md": "16px",
  "lg": "24px",
  "xl": "32px",
  "2xl": "48px",
  "3xl": "72px"
} as const;
