// GENERATED by scripts/build-tokens.ts from DESIGN.md. Do not edit; run `npm run build:tokens`.

export const colors = {
  "night": "#0B0D12",
  "surface": "#161A23",
  "rule": "#2A3038",
  "text": "#F2EBDD",
  "text-muted": "#9BA1AD",
  "data-centres": "#FFA630",
  "ai": "#FFF1C9",
  "country": "#7D93B5",
  "forecast": "#B07A2E",
  "band": "#3A2A14",
  "primary": "#FFA630",
  "on-primary": "#0B0D12",
  "focus": "#FFF1C9",
  "success": "#5FBF8F",
  "warning": "#FF6B5B",
  "error": "#FF6B5B"
} as const;
export type ColorToken = keyof typeof colors;

export const rounded = {
  "sm": "3px",
  "md": "6px",
  "full": "9999px"
} as const;
export const spacing = {
  "xs": "4px",
  "sm": "8px",
  "md": "16px",
  "lg": "24px",
  "xl": "32px",
  "2xl": "48px",
  "3xl": "72px"
} as const;
